# Generated by Django 4.0 on 2021-12-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre completo')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('course', models.CharField(choices=[('0', 'Lengua'), ('1', 'Programación'), ('2', 'Matemáticas'), ('3', 'Práctica'), ('4', 'Sistemas'), ('5', 'Base de datos'), ('6', 'Modelado'), ('7', 'Arquitectura'), ('8', 'Redes')], max_length=50, verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='NoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre completo')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('office', models.CharField(choices=[('0', 'Finanzas'), ('1', 'RRHH'), ('2', 'Comercial'), ('3', 'Marketing'), ('4', 'Soporte'), ('5', 'Administración'), ('6', 'Contabilidad'), ('7', 'Mantenimiento'), ('8', 'Gestión')], max_length=50, verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'No Docente',
                'verbose_name_plural': 'No Docentes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
