# Generated by Django 4.0 on 2021-12-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_docente_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodocente',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='registro', verbose_name='Imagen'),
        ),
    ]
